### ISSUE TITLE
connect_timeout is not configurable with connect_options

### ISSUE THREAD

**Issue by key-master** [erlcloud/lhttpc#21]
https://github.com/erlcloud/lhttpc/pull/19 introduced parameters configuration with config.
and config `{connect_options, [{connect_timeout, 1000}]}` does not work

**Comment by key-master** [comment]
@motobob please take a look
@egobrain FYI

**Comment by egobrain** [comment]
@key-master https://github.com/erlcloud/lhttpc/pull/23
